version: "3.9"

services:
  game-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["uvicorn", "mock_game_server:app", "--host", "0.0.0.0", "--port", "9000"]
    ports:
      - "9000:9000"

  gateway:
    build: ./backend
    ports:
      - "8000:8000"
      - "9200:9200/udp"
    environment:
      - UPSTREAM_GAME_SERVER=http://game-server:9000
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - redis
      - game-server

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - gateway

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - gateway
