apiVersion: v1
kind: Service
metadata:
  name: vanguard-gateway
spec:
  selector:
    app: vanguard-gateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: udp
      port: 9200
      targetPort: 9200
      protocol: UDP
  type: ClusterIP
